{
 "title": "UDP CLIENT METRICS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "VIP",
    "query": "SELECT vip FROM udp_client_vip_metrics"
   },
   {
    "name": "METHOD",
    "query": "SELECT method FROM udp_client_url_metrics"
   },
   {
    "name": "HOST_IP",
    "query": "SELECT host_ip FROM udp_client_url_metrics"
   },
   { "name": "URL", "query": "SELECT uri FROM error_metrics" },
   {
    "name": "START_TIME",
    "query": "SELECT CAST(start_time at time zone 'utc' at time zone 'Asia/Kolkata' as Varchar(25)) FROM running_configs"
   }
  ]
 },
 "panels": [
  {
   "title": "UDP SESSION METRICS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sessions,cycles_complete,reqs_sent,reqs_failed,dg_sent,dg_send_fail,resp_rcvd,dg_recd\nFROM udp_client_ses_metrics\nWHERE\n  $__timeFilter(ts) and host_ip IN($HOST_IP)"
    }
   ]
  },
  {
   "title": "UDP VIP METRICS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  sessions\nFROM udp_client_vip_metrics\nWHERE\n  $__timeFilter(ts) and vip IN($VIP) and host_ip IN($HOST_IP)"
    }
   ]
  },
  {
   "title": "UDP URL METRICS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  reqs_sent,reqs_failed,dg_sent,dg_send_fail,resp_rcvd,dg_recd\nFROM udp_client_url_metrics\nWHERE\n  $__timeFilter(ts) and host_ip IN($HOST_IP) and vip IN($VIP) and method IN($METHOD)"
    }
   ]
  },
  {
   "title": "LATENCY METRICS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  mean_latency,var_latency,latency_min,latency_max\nFROM udp_client_url_metrics\nWHERE\n  $__timeFilter(ts)"
    }
   ]
  }
 ]
}